javac Animal.java
javac Axe.java
javac Carrot.java
javac Consumable.java
javac Corn.java
javac Crow.java
javac Equipment.java
javac EquipmentManager.java
javac Exterior.java
javac Field.java
javac Firework.java
javac Forest.java
javac Gold.java
javac GoldPieces.java
javac Hammer.java
javac Hoe.java
javac IArea.java
javac IInventory.java
javac Iron.java
javac IUsable.java
javac Lumber.java
javac Main.java
javac Mine.java
javac Neighbor.java
javac OptimalTool.java
javac Ore.java
javac Person.java
javac Player.java
javac Scarecrow.java
javac Seed.java
javac Sheep.java
javac Shovel.java
javac Structure.java
javac Tool.java
javac Trader.java
javac Watermelon.java
javac Window.java
javac World.java